import { Inter } from 'next/font/google'
import './globals.css'
import HeaderTop from './Components/HeaderTop'
import Header from './Components/Header'
import Navbar from './Components/Navbar'
import Footer from './Components/Footer'
import Hero from './Components/Hero'
import Services from './Components/Services'
import Pizza from './Components/Pizza'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop />
        <Header />
        <Navbar />
        <Hero />
        <Services />
        <Pizza />
        {children}
        <Footer />
        </body>
    </html>
  )
}
